name: Generate terraform docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: .
          git-push: "true"
          output-file: docs/terraform.md
          output-method: inject
          config-file: ".terraform-docs.yaml"
