name: Validate PR commit messages

on:
  pull_request:
    branches: ["*"] # should be changed to main after checking that the config is correct

jobs:
  commitlint:
    name: Validate commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install commitlint
        run: |
          npm install commitlint @commitlint/config-conventional @commitlint/cli

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
