name: Publish a new Github Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
