name: Release

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "**/*.tpl"
      - "**/*.py"
      - "**/*.tf"
      - "**/*.yaml"
      - "**/*.yml"
      - ".github/workflows/release.yaml"

jobs:
  release:
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'cyberlabrs'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
