name: Release

on:
  pull_request:
    branches: ["*"] # should be changed to main after checking that the config is correct
    #types: ["closed"] # should be uncommented after checking that the config is correct
    paths-ignore:
      - ".github"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - "commitlint.config.js"

jobs:
  release:
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'cyberlabrs' #&& github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: true # should be removed after checking that the config is correct
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
