name: Release

on:
  pull_request:
    branches: ["main"]
    types: ["closed"]
    paths-ignore:
      - ".github"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - "commitlint.config.js"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    # Skip running release workflow on forks
    if: github.event.pull_request.merged == true && github.repository_owner == 'cyberlabrs'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        with:
          ci: false # required to allow running on PR merged instead of push to main
          branches: |
            ["main"]
          tag_format: ${version}
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
