name: Release

on:
  pull_request:
    branches: ["main"]
    types: ["closed"]
    paths-ignore:
      - ".github"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - "commitlint.config.js"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.event.pull_request.merged == true && github.repository_owner == 'cyberlabrs'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ci: false # required to allow running on PR merged instead of push to main
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
