name: Release

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "**/*.tpl"
      - "**/*.py"
      - "**/*.tf"
      - "**/*.yaml"
      - "**/*.yml"
      - ".github/workflows/release.yaml"

jobs:
  release:
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'cyberlabrs'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dryRun: true # should be removed after checking that the config is correct
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
