name: Release

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - "commitlint.config.js"

jobs:
  release:
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: |
            ["*"]
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
