name: Terraform docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: terraform-docs/gh-actions@v1
        with:
          git-push: "true"
